### ISSUE TITLE
ERROR: null value in column "municipality_id"

### ISSUE THREAD

**Issue by hbokh** [Sjors/crush_curve#12]
Hoi Sjors,

Net vers gecloned, maar het loopt vast op de `rake data:fetch`.
PostgreSQL-error:

```
2020-10-03 14:46:51.981 CEST [350] ERROR:  null value in column "municipality_id" violates not-null constraint
2020-10-03 14:46:51.981 CEST [350] DETAIL:  Failing row contains (2, null, 2020-03-13 00:00:00, null, null, null, 2020-10-03 12:46:51.980269, 2020-10-03 12:46:51.980269, null, f, f).
2020-10-03 14:46:51.981 CEST [350] STATEMENT:  INSERT INTO "cases" ("day", "created_at", "updated_at") VALUES ($1, $2, $3) RETURNING "id
```

Rake nagenoeg vergelijkbaar natuurlijk:

```
# rake data:fetch
Downloading CSV...
Parsing CSV...
Processing records...
rake aborted!
ActiveRecord::NotNullViolation: PG::NotNullViolation: ERROR:  null value in column "municipality_id" violates not-null constraint
DETAIL:  Failing row contains (2, null, 2020-03-13 00:00:00, null, null, null, 2020-10-03 12:46:51.980269, 2020-10-03 12:46:51.980269, null, f, f).
/usr/local/lib/ruby/gems/2.7.0/gems/activerecord-6.0.3.2/lib/active_record/connection_adapters/postgresql_adapter.rb:675:in `exec_params'
/usr/local/lib/ruby/gems/2.7.0/gems/activerecord-6.0.3.2/lib/active_record/connection_adapters/postgresql_adapter.rb:675:in `block (2 levels) in exec_no_cache'
/usr/local/lib/ruby/gems/2.7.0/gems/activesupport-6.0.3.2/lib/active_support/dependencies/interlock.rb:48:in `block in permit_concurrent_loads'

...
```

Heb de DB al eens gedropt en opnieuw aangemaakt plus de gesuggereerde `rails db:migrate` gedraaid.
Ik heb alleen dit als aanwijzing: https://github.com/Sjors/crush_curve/blob/master/db/schema.rb#L19

Draai op macOS Mojave, met PostgreSQL 12.4, rake 13.0.1 maar heb niet de indruk dat het een versie probleem van de software is op dit moment.

Enig idee? Bij voorbaat dank!

**Comment by hbokh** [comment]
Als ik dit draai gaat het wel goed:

```
bin/rake db:seed
bin/rake data:fetch
```

Maar vervolgens gaat `bin/rails s` fout zodra ik de pagina in de browser laad.

**Comment by Sjors** [comment]
Eventuele verduidelijking van de README is altijd welkom!
